### ISSUE TITLE
Could you provide a code coverage badge?

### ISSUE THREAD

**Issue by nguyenxndaidev** [fluttercommunity/get_it#192]
Could you provide a code coverage badge?

Ex. https://github.com/marketplace/actions/codecov

**Comment by escamoteur** [comment]
Unfortunately I didn't really found to look into it how to setup this correctly.

**Comment by nguyenxndaidev** [comment]
1. you need to register your project on codecov.io
2. Just add a step like what I am doing in my package. For opensource public package, you don't need to send a token. The main thing is to make sure the lcov.info path is correct and start from the root of your repository.

This is my config: https://github.com/zenonine/navi/blob/master/.github/workflows/verify-navi.yml

```
- uses: codecov/codecov-action@v1
        with:
          files: ./navi/coverage/lcov.info
```

**Comment by escamoteur** [comment]
that's a github action?

**Comment by nguyenxndaidev** [comment]
`codecov/codecov-action@v1` is a github action. Yes.

**Comment by nguyenxndaidev** [comment]
I am seeing you are using it, right?

https://github.com/fluttercommunity/get_it/blob/master/.github/workflows/dart.yml

```
    # Code coverage can be acitivated once its ready.
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
```
